import { specialist, type SpecialistDepartment } from './types.js';

export const apexControlDepartment: SpecialistDepartment = {
  id: 'apex-control',
  name: 'APEX Control Plane',
  lead: 'APEX Commander',
  defaultRole: 'CEO',
  revenuePriority: 5,
  purpose: 'Operate and improve APEX orchestration, providers, mission control, cost, reliability, QA, release, telemetry, and product strategy.',
  defaultActivation: ['apex-commander','mission-control','agent-supervisor','orchestrator-auditor','llm-director','provider-watch','revenue-ops','conversion-lab','cost-governor','reliability-engineer','apex-qa','release-commander','telemetry','product-strategist'],
  profiles: [
    specialist('apex-commander', 'APEX Commander', 'CEO', 'Coordinate control-plane missions across runtime, business, engineering, and reliability while preserving operator authority.'),
    specialist('mission-control', 'Mission Control', 'CEO', 'Maintain mission and task state, dependency visibility, priorities, blockers, checkpoints, and completion evidence.'),
    specialist('agent-supervisor', 'Agent Supervisor', 'CTO', 'Monitor workforce liveness, task ownership, stuck agents, queue behavior, and safe recovery paths.'),
    specialist('orchestrator-auditor', 'Orchestrator Auditor', 'QA_DIRECTOR', 'Audit delegation, deduplication, checkpoints, approvals, task routing, and orchestration correctness.'),
    specialist('llm-director', 'LLM Director', 'CTO', 'Own model-routing policy, capability fit, evidence-based routing, tool-call reliability, and serving-model observability.'),
    specialist('provider-watch', 'Provider Watch', 'DEVOPS', 'Track provider availability, quotas, cooldowns, authentication, latency, errors, and fallback health.'),
    specialist('lead-engine', 'Lead Engine', 'LEAD_RESEARCH', 'Audit and improve lead discovery, enrichment, provenance, deduplication, and ICP fit across the APEX pipeline.'),
    specialist('research-engine', 'Research Engine', 'LEAD_RESEARCH', 'Audit and improve business and web research workflows, sourcing quality, evidence capture, and throughput.'),
    specialist('campaign-engine-specialist', 'Campaign Engine', 'SALES', 'Audit and improve campaign generation, segmentation, sequencing, state transitions, and measurable outcomes.'),
    specialist('outbound-engine', 'Outbound Engine', 'SALES', 'Audit and improve authorized outbound email and call execution, compliance gates, deliverability, retries, and attribution.'),
    specialist('voice-commander', 'Voice Commander', 'LEAD_DEV', 'Coordinate outbound and inbound voice architecture, provider integrations, agent prompts, transfer rules, and call analytics.'),
    specialist('crm-commander', 'CRM Commander', 'SALES', 'Own pipeline-state integrity, contact history, tasks, opportunity progression, attribution, and CRM automation.'),
    specialist('revenue-ops', 'Revenue Ops', 'COO', 'Connect lead volume, outreach, meetings, opportunities, sales, cost, and revenue into one operating view.'),
    specialist('conversion-lab', 'Conversion Lab', 'MARKETING', 'Design controlled experiments across messaging, offers, calls, demos, onboarding, and follow-up with explicit success metrics.'),
    specialist('cost-governor', 'Cost Governor', 'CTO', 'Measure and govern LLM, provider, and infrastructure spend, token usage, retries, unit economics, and waste without hiding failures.'),
    specialist('reliability-engineer', 'Reliability Engineer', 'DEVOPS', 'Own runtime resilience, health signals, queue recovery, idempotency, incident prevention, and self-healing behavior.'),
    specialist('apex-qa', 'APEX QA', 'QA_DIRECTOR', 'Independently verify APEX workflows, tools, dashboards, task completion claims, and regressions using deterministic evidence.'),
    specialist('red-team-apex', 'Red Team APEX', 'QA_DIRECTOR', 'Adversarially test APEX autonomy, approvals, external actions, security, hallucination resistance, and failure recovery.'),
    specialist('release-commander', 'Release Commander', 'DEVOPS', 'Own APEX release provenance, CI evidence, target-environment verification, rollback readiness, and live post-release checks.'),
    specialist('telemetry', 'Telemetry', 'CTO', 'Ensure operational metrics, task outcomes, model and provider attribution, costs, and health data are accurate and actionable.'),
    specialist('product-strategist', 'Product Strategist', 'COO', 'Translate market and customer evidence into APEX product priorities, packaging, positioning, and measurable roadmap decisions.'),
  ],
};
