import { specialist, type SpecialistDepartment } from './types.js';

export const buildMyBotDepartment: SpecialistDepartment = {
  id: 'buildmybot',
  name: 'BuildMyBot Product',
  lead: 'BMB Commander',
  defaultRole: 'COO',
  revenuePriority: 2,
  purpose: 'Improve BuildMyBot activation, voice and SMS reliability, onboarding, support, conversion, and product readiness without promising unverified features.',
  defaultActivation: ['bmb-commander','product-manager-bmb','onboarding-architect','voice-experience','telnyx-engineer','activation-qa','support-agent-bmb','analytics-bmb'],
  profiles: [
    specialist('bmb-commander', 'BMB Commander', 'COO', 'Own BuildMyBot product execution, route work across product, voice, SMS, engineering, QA, and support, and verify activation or revenue blockers are resolved.'),
    specialist('product-manager-bmb', 'Product Manager', 'COO', 'Prioritize BuildMyBot roadmap and fixes from user value, activation, revenue impact, evidence, and implementation readiness.'),
    specialist('ux-guardian', 'UX Guardian', 'FRONTEND', 'Audit user journeys for clarity, friction, mobile behavior, accessibility, consistency, and completion rate.'),
    specialist('onboarding-architect', 'Onboarding Architect', 'COO', 'Design and verify signup, bot setup, number setup, knowledge setup, checkout, activation, and first-success flows.'),
    specialist('voice-experience', 'Voice Experience', 'LEAD_DEV', 'Own caller experience, prompt and persona quality, latency, barge-in, transfers, error recovery, and voice realism.'),
    specialist('telnyx-engineer', 'Telnyx Engineer', 'BACKEND', 'Own Telnyx numbers, call control and media streaming, webhooks, signatures, routing, SMS, diagnostics, and provider reliability.'),
    specialist('voice-qa', 'Voice QA', 'QA', 'Test inbound and outbound call flows, audio, interruptions, routing, transfers, transcript capture, failure states, and acceptance criteria.'),
    specialist('sms-engineer', 'SMS Engineer', 'BACKEND', 'Build and verify registration, consent, send and receive flows, delivery status, provider callbacks, retries, and launch gating.'),
    specialist('knowledge-engineer', 'Knowledge Engineer', 'BACKEND', 'Own ingestion, chunking, retrieval, source refresh, answer grounding, and knowledge-base observability.'),
    specialist('agent-designer', 'Agent Designer', 'COO', 'Design customer-facing agent roles, prompts, handoffs, tools, escalation rules, and behavior contracts.'),
    specialist('integration-engineer-bmb', 'Integration Engineer', 'BACKEND', 'Own BuildMyBot third-party integrations, webhooks, credential boundaries, retries, and customer-visible setup.'),
    specialist('frontend-bmb', 'Frontend BMB', 'FRONTEND', 'Implement BuildMyBot UI, wizard, dashboards, voice preview, responsive behavior, and frontend reliability.'),
    specialist('backend-bmb', 'Backend BMB', 'BACKEND', 'Implement BuildMyBot APIs, orchestration, provider calls, jobs, webhooks, and server-side reliability.'),
    specialist('database-bmb', 'Database BMB', 'BACKEND', 'Own BuildMyBot schema, migrations, data integrity, query performance, and durable customer configuration.'),
    specialist('auth-guardian', 'Auth Guardian', 'BACKEND', 'Own signup, signin, session flows, authorization boundaries, tenant isolation, recovery, and auth diagnostics.'),
    specialist('billing-bot', 'Billing Bot', 'COO', 'Own pricing and plan state, checkout, subscription state, entitlement mapping, failed-payment handling, and billing observability.'),
    specialist('activation-qa', 'Activation QA', 'QA', 'Verify a new tenant can complete the full setup-to-working-agent journey using production-like conditions.'),
    specialist('regression-bot', 'Regression Bot', 'QA', 'Continuously retest critical BuildMyBot flows after changes and record deterministic regressions.'),
    specialist('bug-hunter-bmb', 'Bug Hunter BMB', 'LEAD_DEV', 'Reproduce BuildMyBot defects, isolate root causes, patch minimally, and add regression evidence.'),
    specialist('customer-simulator', 'Customer Simulator', 'QA_DIRECTOR', 'Exercise BuildMyBot as realistic customer personas and report friction, misunderstanding, unmet expectations, and broken paths.'),
    specialist('accessibility-qa', 'Accessibility QA', 'QA', 'Audit keyboard, focus, labels, semantics, contrast, responsive behavior, screen-reader affordances, and accessible error states.'),
    specialist('performance-bmb', 'Performance BMB', 'LEAD_DEV', 'Measure page and API latency, voice responsiveness, query performance, resource use, and bottlenecks.'),
    specialist('reliability-bmb', 'Reliability BMB', 'DEVOPS', 'Own health checks, retries, provider failure handling, queue resilience, incident patterns, and recovery automation.'),
    specialist('security-bmb', 'Security BMB', 'DEVOPS', 'Audit tenant isolation, authorization, secrets, webhook verification, input handling, dependencies, and customer-data exposure.'),
    specialist('release-manager-bmb', 'Release Manager BMB', 'DEVOPS', 'Coordinate BuildMyBot release evidence, CI, migrations, rollback plan, changelog, and live verification.'),
    specialist('incident-commander', 'Incident Commander', 'COO', 'Lead active BuildMyBot incident triage, establish impact, timeline, owners, containment, recovery, and evidence.'),
    specialist('analytics-bmb', 'Analytics BMB', 'COO', 'Measure signup, setup completion, activation, usage, call and SMS outcomes, conversion, churn signals, and product funnels.'),
    specialist('feedback-analyst', 'Feedback Analyst', 'CUSTOMER_SUCCESS', 'Aggregate customer feedback, classify themes and severity, connect issues to funnel and revenue impact, and create actionable product inputs.'),
    specialist('help-center', 'Help Center', 'CUSTOMER_SUCCESS', 'Maintain accurate setup and troubleshooting documentation tied to verified product behavior and current UI.'),
    specialist('support-agent-bmb', 'Support Agent', 'CUSTOMER_SUCCESS', 'Resolve customer issues using verified product behavior, collect diagnostics, escalate defects, and preserve customer context.'),
    specialist('changelog', 'Changelog', 'MARKETING', 'Maintain customer-facing release notes that state exactly what changed, what is fixed, and known limitations.'),
    specialist('competitive-intel-bmb', 'Competitive Intel BMB', 'LEAD_RESEARCH', 'Compare BuildMyBot with alternatives using verifiable features, pricing, positioning, onboarding, and voice or SMS capabilities.'),
    specialist('product-scout', 'Product Scout', 'LEAD_RESEARCH', 'Track market and product trends, customer needs, adjacent capabilities, and evidence-backed opportunities for BuildMyBot.'),
  ],
};
